import google.generativeai as genai
import os
from dotenv import load_dotenv

# Load biến môi trường từ file .env
load_dotenv()

genai.configure(api_key=os.environ["API_KEY"])
model = genai.GenerativeModel("gemini-1.5-flash")
response = model.generate_content(
    "Câu hỏi: 'Nguyên nhân gây rối loạn tiền đình?'"
    "Tài liệu 1: Rối loạn tiền đình là gì ? . Trước khi tìm hiểu rối loạn tiền đình là gì chúng ta hãy tìm hiểu vai trò của tiền đình với cơ thể . Theo đó , tiền đình chính là bộ phận ở sau hai bên ốc tai . Tiền đình có nhiệm vụ giúp cơ thể duy trì tư thế thăng bằng , cũng như phối hợp nhuần nhuyễn các cử động của tay , chân , thân mình . Rối loạn tiền đình là tình trạng dây thần kinh số 8 ở tiền đình bị tổn thương , dẫn tới thông tin dẫn truyền bị sai lệch . Cơ thể vì thế nên không giữ được sự thăng bằng , dễ bị lảo đảo , chóng mặt và hoa mắt . Thậm chí là dễ bị ngã nếu di chuyển . (Score: 7.0492)"
    "Tài liệu 2: Rối loạn tiền đình là gì ? . Trước khi tìm hiểu cách chữa rối loạn tiền đình bằng củ gừng , chúng ta cần phải làm rõ rối loạn tiền đình là gì . Trước hết , rối loạn tiền đình là tình trạng rối loạn hoặc tắc nghẽn ở dây thần kinh số 8 . Điều này khiến cho quá trình truyền dẫn và tiếp nhận thông tin ở tiền đình bị cản trở . Từ đó , dẫn đến các tổn thương khác ở mạch máu và hai bán cầu não . Rối loạn tiền đình được chia thành 2 loại : Rối loạn tiền đình ngoại biên : Trên thực tế , đây là loại lành tính nhất của rối loạn tiền đình . Khi mắc phải căn bệnh này , người bệnh thường có dấu hiệu chóng mặt , buồn nôn , nặng đầu , khó tập trung , ù tai , ... khi thay đổi tư thế . Với những người mắc rối loạn tiền đình ngoại biên mãn tính , việc đứng lên , di chuyển là vô cùng khó khăn . Rối loạn tiền đình trung ương : Trường hợp rối loạn tiền đình này thường nguy hiểm hơn , xuất phát từ tình trạng thiểu năng tuần hoàn não . Các triệu chứng của căn bệnh này cũng nghiêm trọng hơn , bao gồm : Choáng váng , chóng mặt , thậm chí là nôn ói , ... (Score: 6.3213)"
    "Tài liệu 3: Vậy hội chứng tiền đình ngoại biên là gì ? . Có thể chia rối loạn tiền đình thành 2 loại là rối loạn tiền đình trung ương và rối loạn tiền đình ngoại biên . Rối loạn tiền đình ngoại biên là một loại phổ biến hơn , chiếm tới 80 % các trường hợp rối loạn tiền đình . Tỷ lệ bệnh nhân bị rối loạn tiền đình trung ương hiện chỉ khoảng 20 % . (Score: 6.2631)"
    "Tài liệu 4:Đau đầu ù tai là bệnh gì ? . Đau đầu ù tai có thể là dấu hiệu cảnh báo cho biết bạn đã mắc phải một số bệnh lý sau : Bệnh lý đau nửa đầu . Những cơn đau đầu thường bắt nguồn từ dây thần kinh sọ lớn nhất ở cơ thể . Tình trạng đau nửa đầu khi lặp đi lặp lại nhiều lần sẽ gây ra sự kích thích đối với dây thần kinh thính giác và khiến cho bệnh nhân bị đau đầu , ù tai . Thông thường , bệnh nhân sẽ có cảm giác bị đau nửa đầu và ù tai ở cùng một bên . Những cơn đau có thể gây ra nhiều mối nguy hiểm cho bệnh nhân như giảm thị lực , đột quỵ … Rối loạn tiền đình . Hiện tượng ù tai , xuất hiện tiếng ve kêu râm ran ở trong tai , đau đầu , chóng mặt là dấu hiệu cảnh báo của căn bệnh rối loạn tiền đình . Bệnh lý này sẽ khiến cho bạn bị chóng mặt , mất thăng bằng , suy giảm thính lực … Bệnh lý tăng huyết áp nội sọ vô căn . Căn bệnh tăng huyết áp nội sọ thường gây ra một số triệu chứng như rối loạn thị lực , đau đầu , đau tai , ù tai , nghe thấy tiếng đập ở trong tim . Căn bệnh này rất dễ nhầm lẫn với bệnh lý đau nửa đầu . Chính vì vậy , khi phát hiện ra các triệu chứng bệnh lý , bạn nên đến các cơ sở chuyên khoa để được thăm khám và điều trị . Vùng đầu cổ bị chấn thương . Chấn thương sọ não hay các chấn thương đầu cổ khác có thể gây ra sự tổn thương đối với dây thần kinh . Điều này sẽ khiến cho lưu lượng máu lưu thông đến não bộ bị ảnh hưởng . Bệnh nhân lúc này sẽ gặp phải các vấn đề về cơ bắp , thần kinh , từ đó gây ra triệu chứng ù tai , đau đầu . Do rối loạn khớp thái dương hàm . Khi khớp thái dương hàm bị rối loạn và tổn thương sẽ gây ra triệu chứng ù tai kết hợp với đau đầu . Trong trường hợp này , khi điều trị những triệu chứng rối loạn khớp thái dương hàm sẽ giúp bạn làm giảm cảm giác đau đầu và ù tai . (Score: 6.1294)"
    "Tài liệu 5:Những triệu chứng rối loạn tiền đình sau sinh . Các triệu chứng tiền đình khiến người phụ nữ sau sinh thường gặp nhiều nhất là hoa mắt chóng mặt . Một số triệu chứng khác : Đau đầu , buồn nôn : Những triệu chứng này thường xuyên diễn ra và có thể gây ra cảm giác mệt mỏi , uể oải . Ù tai , suy giảm thính lực : Đây là những triệu chứng liên quan đến hệ thống thính giác . Mất khả năng định hướng và giữ thăng bằng : Điều này có thể gây khó khăn trong việc đi lại , đứng ngồi . Giảm khả năng tập trung , chú ý : Ảnh hưởng đến khả năng hoạt động hàng ngày , có thể lơ đãng quên một số việc quan trọng . Cảm giác lo lắng , bất an : Khi triệu chứng dần tiến triển nặng có thể gây trầm cảm sau sinh . (Score: 5.6121)"
    "Hãy trả lời câu hỏi dựa trên các tài liệu trên"
)
print(response.text)